# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00f719e844fe7e6793e6f8e6f3c8e2f352c10c249a7aa09ba9acb6e366cb17072722ec87fee16921fe78223a8870c3198b91efd45dba0e79c8485ba5929f3a29

test:
  secret_key_base: 09e05a56a66ed93b53113e5c853c87b4046f80a67930dcfb51ce26e801b6381ed7f9e735d532a510c10daee63bc50daa905ea067b629103935032dcc3890320f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
